#+title: The building blocks of artificial neural networks: tensors
#+description: Practice
#+colordes: #dc7309
#+slug: pt-07-tensor
#+weight: 7

PyTorch's central object is the /tensor/. Tensors have many similarities with NumPy's /ndarrays/, but they can be computed on GPUs. They are extremely well suited to build neural networks.

In this lesson, we will explore tensors: how to create them, run operations on them, and most importantly, what they really represent. *Run all the code so that you can look at the outputs and explore on your own.*

* Activate your Python virtual environment

After you ~ssh~ to the training cluster, activate the virtual environment that [[https://westgrid-ml.netlify.app/schoolremake/pt-02-cluster.html#headline-4][you created]] so that you have access to the Python packages [[https://westgrid-ml.netlify.app/schoolremake/pt-02-cluster.html#headline-7][you installed]] in it:

#+BEGIN_src sh
$ source ~/env/bin/activate
#+END_src

* Start an interactive job

For instance:

#+BEGIN_src sh
$ salloc --cpus-per-task=1 --mem=3G --time=0:30:0
#+END_src

You can now start an interactive Python session:

#+BEGIN_src sh
$ python
#+END_src

* Load PyTorch

First, we need to load the ~torch~ package:

#+BEGIN_src python
import torch
#+END_src

* Dimensions and sizes

PyTorch's /tensors/ are homogeneous multidimensional arrays.

You can create them with a variety of methods such as:

- ~torch.rand~, for a tensor filled with random numbers from a uniform distribution on \([0, 1)\)
- ~torch.randn~, for a tensor filled with numbers from the standard normal distribution
- ~torch.empty~, for an uninitialized tensor
- ~torch.zeros~, for a tensor filled with \(0\)
- ~torch.ones~, for a tensor filled with \(1\)

Each element you pass to these methods represents the length of one dimension. Consequently, the number of elements determines the number of dimensions of the tensor.

{{<br>}}
_Let's have a look at a few examples:_

#+BEGIN_src python
print(torch.rand(1))
#+END_src

This is a one-dimensional tensor. Its length in the unique dimesion is 1. So it is a tensor with a single element.

When a tensor has a unique element, that element can be returned as a number with the method ~item~:

#+BEGIN_src python
print(torch.rand(1).item())
#+END_src

{{<br>}}

#+BEGIN_src python
print(torch.rand(2))
#+END_src

This is another one-dimensional tensor. Its length in the unique dimesion is 2.

{{<br>}}

#+BEGIN_src python
print(torch.rand(3))
#+END_src

A one-dimensional tensor. Its length in the unique dimesion is 3.

{{<br>}}

#+BEGIN_src python
print(torch.rand(1, 1))
print(torch.rand(1, 1).item())
#+END_src

A two-dimensional tensor. Its length in one dimesion is 1 and its length in the other dimesion is also 1. So this is also a tensor with a single element.

{{<br>}}

#+BEGIN_src python
print(torch.rand(1, 1, 1))
#+END_src

A three-dimensional tensor with a single element.

{{<br>}}

#+BEGIN_src python
print(torch.rand(3, 1))
#+END_src

A two-dimensional tensor. Its length in one dimension is 3 and in the other, 1.

{{<br>}}

#+BEGIN_src python
print(torch.rand(2, 6))
#+END_src

A two-dimensional tensor. Its length in one dimension is 2 and in the other, 6.

{{<br>}}

#+BEGIN_src python
print(torch.rand(2, 1, 5))
#+END_src

A three-dimensional tensor. Its length in one dimension is 2, in a second dimension it is 1, and in the third dimension it is 5.

{{<br>}}

Play with a few more examples until this all makes sense:

#+BEGIN_src python
print(torch.rand(2, 2, 5))
print(torch.rand(1, 1, 5))
print(torch.rand(1, 1, 5, 1))
print(torch.rand(2, 3, 5, 2))
print(torch.rand(2, 3, 5, 2, 4))
print(torch.rand(3, 5, 4, 2, 1))
#+END_src

** Getting information

You can get the dimension of a tensor with the method ~dim~:

#+BEGIN_src python
print(torch.rand(3, 5, 4, 2, 1).dim())
#+END_src

And its size with the method ~size~:

#+BEGIN_src python
print(torch.rand(3, 5, 4, 2, 1).size())
#+END_src

** Creating new tensors of the size of existing ones

All these methods to create tensor can be appended with ~_like~ to create new tensors of the same size:

#+BEGIN_src python
x = torch.rand(2, 4)
print(x)

y = torch.zeros_like(x)
print(y)

x.size() == y.size()
#+END_src

* Operations

Let's take the addition as an example:

/Note: you need to have tensors of matching dimensions./

#+BEGIN_src python
x = torch.rand(2)
y = torch.rand(2)

print(x)
print(y)
#+END_src

The addition can be done with either of:

#+BEGIN_src python
print(x + y)
print(torch.add(x, y))
#+END_src

** In-place operations

In in-place operations, operators are post-fixed with ~_~:

#+BEGIN_src python
print(x)

x.add_(y)
print(x)

x.zero_()
print(x)
#+END_src

* Data type

PyTorch as a {{<b>}}dtype{{</b>}} class similar to that of NumPy.

# xxxxlook at _like

* GPU

Tensors can be sent to a device (CPU or GPU) with the ~to~ method:

* Comments & questions
