#+title: Introduction to the course & cluster access
#+description: Zoom
#+colordes: #e86e0a
#+slug: 01_pt_intro
#+weight: 1

#+OPTIONS: toc:nil

*Zoom session 1*

#+BEGIN_simplebox
/Access:/ {{<n>}}{{<s>}}You should have received the meeting id and password by email

/Time:/ {{<n>}}{{<m>}}9 am Pacific Time

/Topics:/
{{<n>}}{{<n>}}Presentation of the course \\
{{<n>}}{{<s>}}{{<m>}}{{<m>}}{{<m>}}Distribution of usernames and password \\
{{<n>}}{{<s>}}{{<m>}}{{<m>}}{{<m>}}Access to the JupyterHub for this course \\
{{<n>}}{{<s>}}{{<m>}}{{<m>}}{{<m>}}Access to the training cluster for this course
#+END_simplebox
{{<br>}}

For this course, we will use our training cluster UU (readers of Terry Pratchett may smile).

For interactive jobs requiring little computing power, we will use a JupyterHub running on UU and using few resources. We could run such jobs with ~salloc~ from an SSH session, but JupyterLab creates a friendly interface. \\
This is a good place to develop and try code, explore data, etc.

When we need lots of computing power however—for instance while training models—we will SSH to the training cluster and run ~sbatch~ jobs. \\
Training models from Jupyter would be a poor use of computing resources: while large amounts of memory, many CPUs and a GPU are useful to train models, having them allocated for an entire Jupyter session would have them sit idle for most of the time. This is something to think about when you use the real Compute Canada clusters!

* JupyterLab

To launch JupyterLab on UU:

1. Go to [[https:uu.c3.ca]]
2. Sign in with your username and password
3. *Please leave the following untouched:* \\
   {{<m>}}Reservation: "None" \\
   {{<m>}}Account: "def-sponsor00" \\
   {{<m>}}Number of cores: "1" \\
   {{<m>}}GPU configuration: "None" \\
   *These are the only values you should edit:* \\
   {{<m>}}Change the time to *8.0* \\
   {{<m>}}Change the memory to *2000* \\
   {{<m>}}Make sure the interface is set to *JupyterLab*
4. Press start
* Comments & questions
