#+title: Our NN to classify the MNIST
#+description: Zoom
#+colordes: #e86e0a
#+slug: 14_pt_ournn
#+weight: 14

#+BEGIN_simplebox
*Zoom session 3 — part 1*

/Time:/ {{<m>}}3 pm Pacific Time. \\
/Topic:/ {{<m>}}In this session, we will build our own NN to classify the MNIST.
#+END_simplebox

* Let's try to run our model

Jupyter is a great tool xxxx. let's move to .... sbatch.

** Log in the training cluster

Open a terminal and SSH to our training cluster [[https://westgrid-ml.netlify.app/autumnschool2020/01_pt_intro/#headline-3][as we saw in the first lesson]].

** Load necessary module

First, we need to load some modules. This is done with the [[https://github.com/TACC/Lmod][Lmod]] tool through the [[https://docs.computecanada.ca/wiki/Utiliser_des_modules/en][module]] command. Here are some key [[https://lmod.readthedocs.io/en/latest/010_user.html][commands]]:

#+BEGIN_src sh
# Get help on the module command
$ module help

# List modules that are already loaded
$ module list

# See which modules are available for a tool
$ module avail <tool>

# Load a module
$ module load <module>[/<version>]
#+END_src

The only tool we need here is Python. \\
~module avail python~ gives us the list of available modules for Python and if we want to load the default module (~python/3.7.4~), all we have to run is:

#+BEGIN_src sh
$ module load python
#+END_src

** Install Python packages

You also need Python packages.

For this, create a virtual environment in which you will install packages with {{<c>}}pip{{</c>}}.

#+BEGIN_box
*Do not use Anaconda* \\
While Anaconda is a great tool on personal computers, it is not an appropriate tool when working on the Compute Canada clusters: binaries are unoptimized for those clusters and library paths are inconsistent with their architecture. Anaconda installs packages in {{<b>}}$HOME{{</b>}} where it creates a very large number of small files. It can also create conflicts by modifying {{<b>}}.bashrc{{</b>}}.
#+END_box

Create a virtual environment:

#+BEGIN_src sh
$ virtualenv --no-download ~/env
#+END_src

Activate your virtual environment:

#+BEGIN_src sh
$ source ~/env/bin/activate
#+END_src

Update pip:

#+BEGIN_src sh
(env) $ pip install --no-index --upgrade pip
#+END_src

Install the packages you need in the virtual environment:

#+BEGIN_src sh
(env) $ pip install --no-index matplotlib torch torchvision
#+END_src

#+BEGIN_mhexample
If you want to exit the virtual environment, you can press Ctrl-D or run:
#+END_mhexample

#+BEGIN_src sh
(env) $ deactivate
#+END_src

** Write a Python script

Create a directory for this project and ~cd~ into it:

#+BEGIN_src sh
mkdir mnist
cd mnist
#+END_src

Start a Python script with the text editor of your choice:

#+BEGIN_src sh
nano nn.py
#+END_src

** Write a Slurm script

Write a shell script with the text editor of your choice:

#+BEGIN_src sh
nano nn.sh
#+END_src

This is what you want in that script:

#+BEGIN_src sh
#!/bin/bash
#SBATCH --time=5:0
#SBATCH --cpus-per-task=1
#SBATCH --mem=2G
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

python ~/mnist/nn.py
#+END_src

#+BEGIN_mhexample
Notes:
- ~--time~ accepts these formats: "min", "min:s", "h:min:s", "d-h", "d-h:min" & "d-h:min:s"
- ~%x~ will get replaced by the script name & ~%j~ by the job number
#+END_mhexample

* Comments & questions
