#+title: Installing Python and PyTorch
#+description: Practice
#+colordes: #dc7309
#+slug: pt-04-install
#+weight: 4

{{<br>}}
/All installations are local (on your machine). Don't worry about the cluster./

* Miniconda

First of all, you need *Python 3.7 or higher*.\\
Then you need *a package manager* to install Python packages.

There are many ways to go about this and you are free to chose an alternative method if you wish to do so, particularly if you already have Python installed and are used to installing new packages.

For those new to Python, *I suggest installing [[https://docs.conda.io/en/latest/miniconda.html][Miniconda3]]*.\\
This will install Python 3.7, the package manager conda, and only the packages they need.\\
This is a much smaller installation than Anaconda.

* PyTorch

Lastly, you need to install *PyTorch*.

Use [[https://pytorch.org/get-started/locally/][this page]] to find the command you need to run based on your operating system and whether or not you have CUDA (this only concerns you if you have an Nvidia GPU).

I recommend using the *Stable (1.5) build*.

/Examples:/

- You are on Windows, you installed conda as suggested above, and you do not have CUDA, then run:

#+BEGIN_src sh
conda install pytorch torchvision cpuonly -c pytorch
#+END_src

- You are on a Mac, you already had conda because you had installed Anaconda prior to this workshop, and you do not have CUDA, then run:

#+BEGIN_src sh
conda install pytorch torchvision -c pytorch
#+END_src

- Etc.

* Test the installation

Make sure that all works well by launching Python, loading the {{<c>}}torch{{</c>}} package and creating a 2-dimensional tensor of zeros:

{{<i>}}
#+BEGIN_src python
from __future__ import print_function
import torch

torch.zeros(3, 4)
#+END_src

{{<o>}}
#+BEGIN_src python
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
#+END_src

/Note:/ if you have a CUDA-enabled GPU on your machine and you want to test whether it is accessible to PyTorch, you can run:

{{<i>}}
#+BEGIN_src python
torch.cuda.is_available()
#+END_src

This should return {{<c>}}True{{</c>}}.

* Issues

If you have issues installing Python and/or PyTorch, please sign up for the [[https://westgrid-ml.netlify.app/school/pt-05-debug.html][debug session]] to make sure that you have a running installation before our next Zoom meeting (we will not have time to debug installation issues during that meeting).

* Comments & questions
