#+title: What are neural networks & how do they learn?
#+description: Video
#+colordes: #663300
#+slug: 03_nn
#+weight: 3

* What are NN? (19 min)

[[https://www.3blue1brown.com/][3Blue1Brown by Grant Sanderson]] has a series of 4 videos on neural networks which is easy to watch, fun, and does an excellent job at introducing the functioning of a simple neural network.

For this lesson, you will watch the first of these videos which explains what NN are.

#+BEGIN_note
Watch it beyond the acknowledgement fragment as the function ReLU (a really important function in modern neural networks) is introduced at the very end.{{<2br>}}
#+END_note

{{<youtube aircAruvnKk>}} {{<br>}}

#+BEGIN_note
As you develop your own ML models, if you find that your mathematical background is shaky, 3blue1brown also has [[https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab][an excellent series of videos on linear algebra]] and [[https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr][an equally great one on calculus]].
#+END_note

* How do NN learn? (21 min)

In this lesson, you will watch the second video on NN by [[https://www.3blue1brown.com/][3Blue1Brown]] which explains how neural networks learn.{{<2br>}}

{{<youtube IHZwWFHWa-w>}}

* What is backpropagation? (14 min)

In this lesson, you will watch the third video on NN by [[https://www.3blue1brown.com/][3Blue1Brown]] which explains how backpropagation works.{{<2br>}}

{{<youtube Ilg3gGewQ5U>}}{{<br>}}

#+BEGIN_note
There is one minor terminological error in this video: they call the use of mini-batches *stochastic gradient descent*. In fact, this is called *mini-batch gradient descent*. Stochastic gradient descent uses a single example at each iteration.
#+END_note

* How does backpropagation work? (10 min)

In this lesson, you will watch the last video on NN by [[https://www.3blue1brown.com/][3Blue1Brown]] which dives into the calculus of backpropagation.{{<2br>}}

{{<youtube tIeHLnjs5U8>}}

* Comments & questions
