#+title: Introduction to the PyTorch course
#+description: Zoom
#+colordes: #cc0066
#+slug: pt-01-intro
#+weight: 1

#+OPTIONS: toc:nil

In this session, I will present the schedule for this machine learning course with PyTorch, I will explain what you have to do before our next meeting, and we will briefly introduce each other. Most importantly, I will give you a username for the training cluster.

Due to space limitations, please note that *only those joining this opening session will get a username*.

#+BEGIN_zoombox
This interactive session will be conducted through Zoom.

The meeting ID and password was emailed to people on the waiting list. If we reach our cap and you cannot get in this meeting, don't worry: you can always practice the material [[https://westgrid-ml.netlify.app/schoolremake/pt-03-local.html][on your machine]] and we will offer many machine learning workshops in the future.
#+END_zoombox

*No recording* will be made during this session so as not to discourage participation.
